config/routes.rb
Rails.application.routes.draw do

  resources :item_categories
  resources :item_taxes
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_categories
  has_one :item_tax
  validates :name, :presence => {:message => "can't be blank."}
  validates :name, uniqueness: true
  validates :rate, numericality: true
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  has_many :items
  validates :name, :presence => {:message => "can't be blank."}
  validates :name, uniqueness: true
end

app/models/item_tax.rb
class ItemTax < ActiveRecord::Base
  belongs_to :item
  validates :tax, :tax_type, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :set_item_categories, only: [:show, :edit, :update, :destroy]

  def index
    @item_categories = ItemCategory.all
  end

  def new
    @item_category = ItemCategory.new
  end

  def create
    @item_category = ItemCategory.new(item_categories_params)
    if @item_category.save
      redirect_to :action => 'index', notice: 'ItemCategory was created Successfully'
    else
      render 'new'
    end
  end

  def update
    if @item_category.update_attributes(item_categories_params)
      redirect_to :action => 'index', notice: 'ItemCategory updated'
    else
      render 'edit'
    end
  end

  def destroy
    @item_category.destroy
    redirect_to :action => 'index', notice: 'ItemCategory destroyed.'
  end

  private

  def item_categories_params
    params.require(:item_category).permit(:name)
  end

  def set_item_categories
    @item_category = ItemCategory.find(params[:id])
  end
end

app/controllers/item_taxes_controller.rb
class ItemTaxesController < ApplicationController
  before_action :set_item_tax, only: [:show, :edit, :update, :destroy]

  def index
    @item_taxes = ItemTax.all
  end

  def new
    @item_tax = ItemTax.new
  end

  def create
    @item_tax = ItemTax.new(item_tax_params)
    if @item_tax.save
      redirect_to :action => 'index', notice: 'ItemTax was created Successfully'
    else
      render 'new'
    end
  end

  def update
    @item_tax = ItemTax.find(params[:id])
    if @item_tax.update_attributes(item_tax_params)
      redirect_to :action => 'index', notice: 'ItemTax was updated Successfully'
    else
      render 'edit'
    end
  end

  def destroy
    @item_tax.destroy
    redirect_to :action => 'index', notice: 'ItemTax destroyed'
  end

  private

  def item_tax_params
    params.require(:item_tax).permit(:item_id, :tax_type, :tax)
  end

  def set_item_tax
    @item_tax = ItemTax.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :destroy, :update]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to :action => 'index', notice: 'Item was created Successfully'
    else
      render 'new'
    end
  end

  def update
    if @item.update_attributes(item_params)
      redirect_to :action => 'index', notice: 'Item was updated Successfully'
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to :action => 'index', notice: 'Item destroyed.'
  end

  private

  def item_params
    params.require(:item).permit(:item_category_id, :name, :rate)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_category_helper.rb
module ItemCategoryHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/item_tax_helper.rb
module ItemTaxHelper
end

app/views/item_categories/edit.html.erb
<%= form_for @item_category, url: { action: "update" }  do |f| %>
  <% if @item_category.errors.any? %>
    <% @item_category.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :Name %>
  <%= f.text_field :name %>
  <%= f.submit "Update ItemCategory" %>
<% end %>
<%= link_to "Back", item_categories_path %>

app/views/item_categories/index.html.erb
<h1>Listing ItemCategory</h1>
<table>
  <thead>
  <% if params[:notice].present? %>
    <h3 class="notice_message"><%= params[:notice] %></h3>
  <% end %>
  <tr>
    <th>ItemCategoryID</th>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @item_categories.each do |item_category| %>
    <tr>
      <td><%= item_category.id %></td>
      <td><%= item_category.name %></td>
      <td><%= link_to "Show", item_category %></td>
      <td><%= link_to "Edit", edit_item_category_path(item_category) %></td>
      <td><%= link_to "Destroy", item_category, method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to "New ItemCategory", new_item_category_path %>

app/views/item_categories/new.html.erb
<%= form_for @item_category, url: { action: "create" }  do |f| %>
  <% if @item_category.errors.any? %>
    <% @item_category.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :Name %>
  <%= f.text_field :name %>
  <%= f.submit "Create ItemCategory" %>
<% end %>
<%= link_to "Back", item_categories_path %>

app/views/item_categories/show.html.erb
<h1>Show ItemCategory</h1>
<table>
  <thead>
  <tr>
    <th>ItemCategoryID</th>
    <th>Name</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @item_category.id %></td>
    <td><%= @item_category.name %></td>
  </tr>
  </tbody>
</table>
<%= link_to "Back", item_categories_path %>

app/views/item_taxes/edit.html.erb
<%= form_for @item_tax, url: { action: "update" }  do |f| %>
  <% if @item_tax.errors.any? %>
    <% @item_tax.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :ItemId %>
  <%= f.text_field :item_id %>
  <%= f.label :TaxType %>
  <%= f.text_field :tax_type%>
  <%= f.label :Tax %>
  <%= f.text_field :tax %>
  <%= f.submit "Update ItemTax" %>
<% end %>
<%= link_to "Back", item_taxes_path %>

app/views/item_taxes/index.html.erb
<h1>Listing ItemTax</h1>
<table>
  <thead>
  <% if params[:notice].present? %>
    <h3 class="notice_message"><%= params[:notice] %></h3>
  <% end %>
  <tr>
    <th>ItemTaxID</th>
    <th>ItemID</th>
    <th>TaxType</th>
    <th>Tax</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @item_taxes.each do |item_tax| %>
    <tr>
      <td><%= item_tax.id %></td>
      <td><%= item_tax.item_id %></td>
      <td><%= item_tax.tax_type %></td>
      <td><%= item_tax.tax %></td>
      <td><%= link_to "Show", item_tax %></td>
      <td><%= link_to "Edit", edit_item_tax_path(item_tax) %></td>
      <td><%= link_to "Destroy", item_tax, method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Item", new_item_tax_path %>

app/views/item_taxes/new.html.erb
<%= form_for @item_tax, url: {action: "create"} do |f| %>
  <% if @item_tax.errors.any? %>
    <% @item_tax.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :ItemId %>
  <%= f.text_field :item_id %>
  <%= f.label :TaxType %>
  <%= f.text_field :tax_type %>
  <%= f.label :Tax %>
  <%= f.text_field :tax %>
  <%= f.submit "Create ItemTax" %>
<% end %>
<%= link_to "Back", item_taxes_path %>

app/views/item_taxes/show.html.erb
<h1>Show ItemTax</h1>
<table>
  <thead>
  <tr><th>ItemTaxID</th>
    <th>ItemID</th>
    <th>TaxType</th>
    <th>Tax</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @item_tax.id %></td>
    <td><%= @item_tax.item_id %></td>
    <td><%= @item_tax.tax_type %></td>
    <td><%= @item_tax.tax %></td>
  </tr>
  </tbody>
</table>
<%= link_to "Back", item_taxes_path %>

app/views/items/edit.html.erb
<%= form_for @item, url: { action: "update" }  do |f| %>
  <% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :ItemCategoryId %>
  <%= f.text_field :item_category_id %>
  <%= f.label :Name %>
  <%= f.text_field :name%>
  <%= f.label :Rate %>
  <%= f.text_field :rate %>
  <%= f.submit "Update Item" %>
<% end %>
<%= link_to "Back", items_path%>

app/views/items/index.html.erb
<h1>Listing Items</h1>
<table>
  <thead>
  <% if params[:notice].present? %>
    <h3 class="notice_message"><%= params[:notice] %></h3>
  <% end %>
  <tr>
    <th>ItemID</th>
    <th>ItemCategoryID</th>
    <th>Name</th>
    <th>Rate</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= item.item_category_id %></td>
      <td><%= item.name %></td>
      <td><%= item.rate %></td>
      <td><%= link_to "Show",item %></td>
      <td><%= link_to "Edit", edit_item_path(item) %></td>
      <td><%= link_to "Destroy", item, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Item", new_item_path %>

app/views/items/new.html.erb
<%= form_for @item, url: {action: "create"} do |f| %>
  <% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :ItemCategoryId %>
  <%= f.text_field :item_category_id %>
  <%= f.label :Name %>
  <%= f.text_field :name %>
  <%= f.label :Rate %>
  <%= f.text_field :rate %>
  <%= f.submit "Create Item" %>
<% end %>
<%= link_to "Back", items_path%>

app/views/items/show.html.erb
<h1>Show Item</h1>
<table>
  <thead>
  <tr><th>ItemID</th>
    <th>ItemCategoryID</th>
    <th>Name</th>
    <th>Rate</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @item.id %></td>
    <td><%= @item.item_category_id %></td>
    <td><%= @item.name %></td>
    <td><%= @item.rate %></td>
  </tr>
  </tbody>
</table>
<%= link_to "Back", items_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>